[build-system]
    requires      = ["hatchling"]
    build-backend = "hatchling.build"

[project]
    name            = "arpi"
    version         = "0.1.0"
    description     = "Add your description here"
    readme          = "README.md"
    requires-python = ">=3.13,<3.14"
    dependencies    = [
    "black>=26.5.1",
    "duckdb>=1.5.3",
    "folium>=0.20.0",
    "gtfs-realtime-bindings>=2.0.0",
    "kedro>=1.4.0",
    "kedro-datasets[matplotlib-matplotlibdataset,pandas-csvdataset,pandas-exceldataset,pandas-jsondataset,pandas-parquetdataset,pandas-plotlydataset]>=9.4.0",
    "kedro-viz>=12.4.0",
    "plotly>=6.1.2",
    "polars>=1.41.1",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "streamlit>=1.45.1",
    "streamlit-folium>=0.27.2",
    "tqdm>=4.67.3",
    "watchdog>=6.0.0",
]

[tool.hatch.build.targets.wheel]
    packages = ["src/arpi"]

[dependency-groups]
    dev = ["black>=25.0.0", "flake8>=7.0.0", "flake8-pyproject>=1.2.3", "isort>=5.13.0", "pytest>=8.0.0"]

[tool.pytest.ini_options]
    testpaths = ["tests"]

[tool.black]
    line-length    = 148
    target-version = ["py313"]

[tool.isort]
    profile     = "black"
    line_length = 148

[tool.flake8]
    max-line-length = 148
    exclude         = [".venv", "__pycache__", ".git"]

[tool.kedro]
    package_name = "arpi"
    project_name = "arpi"
    kedro_init_version = "1.4.0"
    tools = "['Custom Logging', 'Data Structure']"
    example_pipeline = "True"
    source_dir = "src"

[tool.kedro_telemetry]
    project_id = "bc66b7bfb0e14df3b6f0daa88e85ffb6"
